import "./globals.css"
import {Inter} from "next/font/google"
import {Layout} from "antd"
import Sidebar from '@/components/Sidebar/Sidebar';
import "@/assets/font-awesome/css/all.min.css";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";

const inter = Inter({subsets: ["latin"]})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({children}) {
  const {Header, Sider, Content} = Layout

  const siderStyle = {
    textAlign: "center",
    lineHeight: "100vh",
    color: "#fff",
    backgroundColor: "#efecea",
  }

  return (
    <html lang='en'>
      <body className={inter.className}>
      <Layout>
        <Navbar />
        <Sidebar />
      </Layout>
        {children}
      <Footer />
      </body>
    </html>
  )
}
