"use client"
import "./globals.css"
import {Inter} from "next/font/google"
import {Layout} from "antd"

const inter = Inter({subsets: ["latin"]})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({children}) {
  const {Header, Footer, Sider, Content} = Layout

  const siderStyle = {
    textAlign: "center",
    lineHeight: "100vh",
    color: "#fff",
    backgroundColor: "#efecea",
  }

  return (
    <html lang='en'>
      {/* <Sider style={siderStyle}>Sider</Sider> */}
      <body className='body'>{children}</body>
    </html>
  )
}
